export const jsReserved = [
    "abstract",
    "arguments",
    "await",
    "boolean",
    "break",
    "byte",
    "case",
    "catch",
    "char",
    "class",
    "const",
    "continue",
    "debugger",
    "default",
    "delete",
    "do",
    "double",
    "else",
    "enum",
    "eval",
    "export",
    "extends",
    "false",
    "final",
    "finally",
    "float",
    "for",
    "function",
    "goto",
    "if",
    "implements",
    "import",
    "in",
    "instanceof",
    "int",
    "interface",
    "let",
    "long",
    "native",
    "new",
    "null",
    "package",
    "private",
    "protected",
    "public",
    "return",
    "short",
    "static",
    "super",
    "switch",
    "synchronized",
    "this",
    "throw",
    "throws",
    "transient",
    "true",
    "try",
    "typeof",
    "var",
    "void",
    "volatile",
    "while",
    "with",
    "yield",
];

export const jsObjPropMeth = [
    "Array",
    "Date",
    "eval",
    "function",
    "hasOwnProperty",
    "Infinity",
    "isFinite",
    "isNaN",
    "isPrototypeOf",
    "length",
    "Math",
    "NaN",
    "name",
    "Number",
    "Object",
    "prototype",
    "String",
    "toString",
    "undefined",
    "valueOf",
];

export const testArray = [
    "let lineIdx = 0",
    "let accuracy = 0;",
    "one two three",
];

// SOURCE: https://www.tutorialspoint.com/javascript/javascript_builtin_functions.htm
export const jsOther = [
    "constructor()",
    "toExponential()",
    "toFixed()",
    "toLocaleString()",
    "toPrecision()",
    "toString()",
    "valueOf()",
    "toSource()",
    "charAt()",
    "charCodeAt()",
    "concat()",
    "indexOf()",
    "lastIndexOf()",
    "localeCompare()",
    "length()",
    "match()",
    "replace()",
    "search()",
    "slice()",
    "split()",
    "substr()",
    "substring()",
    "toLocaleLowerCase()",
    "toLocaleUpperCase()",
    "toLowerCase()",
    "toString()",
    "toUpperCase()",
    "anchor()",
    "big()",
    "blink()",
    "bold()",
    "fixed()",
    "fontcolor()",
    "fontsize()",
    "italics()",
    "link()",
    "small()",
    "strike()",
    "sub()",
    "sup()",
    "every()",
    "filter()",
    "forEach(())",
    "join()",
    "map()",
    "pop()",
    "push()",
    "reduce()",
    "reduceRight()",
    "reverse()",
    "shift()",
    "slice()",
    "some()",
    "toSource()",
    "sort()",
    "splice()",
    "unshift()",
    "flat()",
    "Date()",
    "getDate()",
    "getDay()",
    "getFullYear()",
    "getHours()",
    "getMilliseconds()",
    "getMinutes()",
    "getMonth()",
    "getSeconds()",
    "getTime()",
    "getTimezoneOffset()",
    "getUTCDate()",
    "getUTCDate()",
    "getUTCDay()",
    "getUTCFullYear()",
    "getUTCHours()",
    "getUTCMilliseconds()",
    "getUTCMinutes()",
    "getUTCMonth()",
    "getUTCSeconds()",
    "getUTCTime()",
    "getUTCTimezoneOffset()",
    "getYear()",
    "setDate()",
    "setFullYear()",
    "setHours()",
    "setMilliseconds()",
    "setMinutes()",
    "setMonth()",
    "setSeconds()",
    "setTime()",
    "setUTCDate()",
    "setUTCFullYear()",
    "setUTCHours()",
    "setUTCMilliseconds()",
    "setUTCMinutes()",
    "setUTCMonth()",
    "setUTCSeconds()",
    "toLocaleDateString()",
    "toLocaleFormat()",
    "toLocaleString()",
    "toLocaleTimeString()",
    "toSource()",
    "toString()",
    "toTimeString()",
    "toUTCString()",
    "Date.parse()",
    "Date.UTC()",
    "Math.abs()",
    "Math.acos()",
    "Math.asin()",
    "Math.atan()",
    "Math.ceil()",
    "Math.cos()",
    "Math.exp()",
    "Mathfloor().",
    "Math.log()",
    "Math.max()",
    "Math.min()",
    "Math.pow()",
    "Math.random()",
    "Math.round()",
    "Math.sin()",
    "Math.sqrt()",
    "Math.tan()",
    "Math.toSource()",
    "exec()",
    "test()",
    "<script></script>",
    "type='module'",
    "src='script.js'",
    "type='text/javascript'",
    "document.write()",
    "//comment",
    "/*Multiline*/",
    "var",
    "let",
    "const",
    "exec()",
    "test()",
    "if(true){}",
    "else",
    "if(){}",
    "switch()",
    "case",
    "default:",
    "break;",
    "export",
    "arr=[]",
    "import{arr}from",
    "document.getElementById()",
    "document.getElementsByClassName()",
    "targetArray=[...common200]",
    "lineIdx=0",
    "capitalOn=false;",
    "accuracy=0;",
    "nextChar=()=>{};",
    "console.log('Error');",
    "input.value=''",
    "div.textContent=''",
    "input.placeholder=''",
    "Math.floor(Math.random()*num)",
    "return;",
    "randomNumbers=[];",
    "while(num.length<=max){}",
    "num+=getRandom(arr)",
    "numbers.push(num);",
    "el.classList.contains('dark')",
    "el.classList.add('dark')",
    "el.classList.remove('dark')",
    "if (){}else{}",
    "switch(el){}",
    "break;",
    "str.split('');",
    "arr[0].toUpperCase();",
    "arr.join('');",
    "arr.forEach((word)=>{});",
    "if(radio.checked===false)",
    "arr.pop();",
    "arr.push(word.concat(''));",
    "key.style.background='red'",
    "doc.addEventListener('keyup',test);",
    "slider.disabled = true;",
    "slider.disabled=false;",
    "if(set.size>0){}",
    "span.innerText=char;",
    "document.createElement('span');",
    ".join('').split.('').entries()",
    "span.className='active-txt-span';",
    "span.id",
    "location.appendChild(span);",
    "setTimeout(()=>{clearDiv();},200);",
    "if(key!==undefined)",
    "textInput.readOnly=true;",
    "viewportHeight=window.innerHeight;",
    "marginTop=calcMarginTop();",
    // "window.addEventListener('resize',setMarginTop);",
    // "window.addEventListener('load',setMarginTop);",
    "input.disabled=false;",
    "textInput.focus();",
    "typedKey=event.key;",
];

export const common100 = [
    "the",
    "of",
    "and",
    "a",
    "to",
    "in",
    "is",
    "you",
    "that",
    "it",
    "he",
    "was",
    "for",
    "on",
    "are",
    "as",
    "with",
    "his",
    "they",
    "I",
    "at",
    "be",
    "this",
    "have",
    "from",
    "or",
    "one",
    "had",
    "by",
    "word",
    "but",
    "not",
    "what",
    "all",
    "were",
    "we",
    "when",
    "your",
    "can",
    "said",
    "there",
    "use",
    "an",
    "each",
    "which",
    "she",
    "do",
    "how",
    "their",
    "if",
    "will",
    "up",
    "other",
    "about",
    "out",
    "many",
    "then",
    "them",
    "these",
    "so",
    "some",
    "her",
    "would",
    "make",
    "like",
    "him",
    "into",
    "time",
    "has",
    "look",
    "two",
    "more",
    "write",
    "go",
    "see",
    "number",
    "no",
    "way",
    "could",
    "people",
    "my",
    "than",
    "first",
    "water",
    "been",
    "call",
    "who",
    "oil",
    "its",
    "now",
    "find",
    "long",
    "down",
    "day",
    "did",
    "get",
    "come",
    "made",
    "may",
    "part",
];

export const common200 = [
    "over",
    "new",
    "sound",
    "take",
    "only",
    "little",
    "work",
    "know",
    "place",
    "year",
    "live",
    "me",
    "back",
    "give",
    "most",
    "very",
    "after",
    "thing",
    "our",
    "just",
    "name",
    "good",
    "sentence",
    "man",
    "think",
    "say",
    "great",
    "where",
    "help",
    "through",
    "much",
    "before",
    "line",
    "right",
    "too",
    "mean",
    "old",
    "any",
    "same",
    "tell",
    "boy",
    "follow",
    "came",
    "want",
    "show",
    "also",
    "around",
    "form",
    "three",
    "small",
    "set",
    "put",
    "end",
    "does",
    "another",
    "well",
    "large",
    "must",
    "big",
    "even",
    "such",
    "because",
    "turn",
    "here",
    "why",
    "ask",
    "went",
    "men",
    "read",
    "need",
    "land",
    "different",
    "home",
    "us",
    "move",
    "try",
    "kind",
    "hand",
    "picture",
    "again",
    "change",
    "off",
    "play",
    "spell",
    "air",
    "away",
    "animal",
    "house",
    "point",
    "page",
    "letter",
    "mother",
    "answer",
    "found",
    "study",
    "still",
    "learn",
    "should",
    "America",
    "world",
];

export const numbers = [
    "0",
    "1",
    "2",
    "3",
    "4",
    "5",
    "6",
    "7",
    "8",
    "9",

    "2025",
    "2024",
    "2023",
    "2022",
    "2021",
    "2020",
    "2019",
    "2018",
    "2017",
    "2016",
    "2015",
    "2014",
    "2013",
    "2012",
    "2011",
    "2010",
    "2009",
    "2008",
    "2007",
    "2006",
    "2005",
    "2004",
    "2003",
    "2002",
    "2001",
    "2000",
    "1999",
    "1998",
    "1997",
    "1996",
    "1995",
    "1994",
    "1993",
    "1992",
    "1991",
    "1990",
    "1989",
    "1988",
    "1987",
    "1986",
    "1985",
    "1984",
    "1983",
];

// export const timeRelated = [
//     "Monday Tuesday Wednesday Thursday Friday Saturday Sunday",
//     "January February March April May June July August September October November December"
// ]

export const digits = ["0", "1", "2", "3", "4", "5", "6", "7", "8", "9"];

export const punctMarks = [",", ".", "!", "?", ":", ";", "-", "'"];

export const tenFastFingers200 = [
    // "the be of and a to in he have it that for they I with as not on she at by this we you do but from or which one would all will there say who make when can more if no man out other so what time up go about than into could state only new year some take come these know see use get like then first any work now may such give over think most even find day also after way many must look before great back through long where much should well people down own just because good each those feel seem how high too place little world very still nation hand old life tell write become here show house both between need mean call develop under last right move thing",

    "about above add after again air all almost always along and answer America and animal another answer are around as ask at away",
    "back been because before below between began being big book both boy but by",
    "can car carry change children city came close come could country cut",
    "day did different do does don't",
    "each earth eat enough even every example eye",
    "face family far father feet few find first follow for form food from found four",
    "girl give good got great group grow",
    "had hand hard has have he head hear help her here high him his home house how",
    "if important in Indian into is its it's",
    "just",
    "keep kind know",
    "land large later learn leave left let letter light life line little live long look",
    "made make man many may me men mean might mile miss most mother move mountain must my",
    "near need never new next night no not now number",
    "of off often oil on one once only open or other our out over own",
    "page paper part people picture place plant play point put",
    "question quick quickly quite",
    "read really right river run",
    "same say said saw see sea second see second set seem sentence she should show side small so soon some something sometimes song soon sound spell start still stop story study such",
    "talk take tell that then the they these thing think this those thought through time three together too took tree try turn two",
    "under until up use",
    "very",
    "was way walk want watch water well went were when where which while who why will with without would word work world write",
    "year you young your",
];

// SOURCE: https://tk.cusd.com/downloads/500highfrequencywords1.pdf
export const common500 = [
    "a able about above across add after again against ago air all almost alone along already also although always am American among an and animal animals another answer any anything are area around as asked at away",

    "back ball be beautiful became because become been before began begin behind being below bet better between big black blue boat body book both bottom box boy bring brought build built but by",

    "called came can can’t cannot car care carefully carry center certain change check children city class close cold come common complete could country course cut ",

    "dark day deep did didn’t different distance do does dog don’t done door down draw dry during",

    "each early earth easy eat either else end English enough even ever every everyone everything example",

    "face fact fall family far fast father feel feet felt few field finally find fine fire first fish five floor follow food foot for form found four friend from front full",

    "game gave get girl give glass go going gold gone good got great green ground group grow ",

    "had half hand happened hard has have he head hear heard heart heavy held help her here high him himself his hold home horse hot hour house how however hundred ",

    "I I’ll I’m ice idea if important in inside instead into is it it’s its itself ",

    "job just",

    "keep kept kind knew know ",

    "land language  large last later lay learn learned least leave leaves left less let letter life light like line list little live lived living long longer look low ",

    "made main make man many map matter may me mean men might mind miss money moon more morning most mother move much must my",

    "name near need never new next night no not nothing notice now number",

    "of off often oh old on once one only open or order other our out outside over own",

    "page paper part past pattern people perhaps person picture piece place plants play point poor possible power probably problem put",

    "question quite ",

    "rain ran read ready real really red remember rest right river road rock room round run",

    "sad  said same sat saw say school sea second see seen sentence set several shall she ship short should show shown side simple since six size sky small snow so some someone something soon sound space special stand start state stay still stood stop story strong study such suddenly summer sun sure surface system",

    "table take talk tall tell ten than that that’s the their them themselves then there these they thing think third this those though thought three through time tiny to today together told too took top toward town tree true try turn turned two",

    "under understand United States until up upon us use usually",

    "very voice",

    "walk walked want warm was watch water way we weather well went were  what when where whether which while white who whole why wide wild will wind winter with within without words work world would write",

    "yes yet you young your ",
];

// SOURCE: https://www.ef.co.uk/english-resources/english-vocabulary/top-3000-words/
export const common3000 = [
    "a abandon ability able abortion about above abroad absence absolute absolutely absorb abuse academic accept access accident accompany accomplish according account accurate accuse achieve achievement acid acknowledge acquire across act action active activist activity actor actress actual actually ad adapt add addition additional address adequate adjust adjustment administration administrator admire admission admit adolescent adopt adult advance advanced advantage adventure advertising advice advise adviser advocate affair affect afford afraid African African-American after afternoon again against age agency agenda agent aggressive ago agree agreement agricultural ah ahead aid aide AIDS aim air aircraft airline airport album alcohol alive all alliance allow ally almost alone along already also alter alternative although always AM amazing American among amount analysis analyst analyze ancient and anger angle angry animal anniversary announce annual another answer anticipate anxiety any anybody anymore anyone anything anyway anywhere apart apartment apparent apparently appeal appear appearance apple application apply appoint appointment appreciate approach appropriate approval approve approximately Arab architect area argue argument arise arm armed army around arrange arrangement arrest arrival arrive art article artist artistic as Asian aside ask asleep aspect assault assert assess assessment asset assign assignment assist assistance assistant associate association assume assumption assure at athlete athletic atmosphere attach attack attempt attend attention attitude attorney attract attractive attribute audience author authority auto available average avoid award aware awareness away awful",
    "baby back background bad badly bag bake balance ball ban band bank bar barely barrel barrier base baseball basic basically basis basket basketball bathroom battery battle be beach bean bear beat beautiful beauty because become bed bedroom beer before begin beginning behavior behind being belief believe bell belong below belt bench bend beneath benefit beside besides best bet better between beyond Bible big bike bill billion bind biological bird birth birthday bit bite black blade blame blanket blind block blood blow blue board boat body bomb bombing bond bone book boom boot border born borrow boss both bother bottle bottom boundary bowl box boy boyfriend brain branch brand bread break breakfast breast breath breathe brick bridge brief briefly bright brilliant bring British broad broken brother brown brush buck budget build building bullet bunch burden burn bury bus business busy but butter button buy buyer by",
    "cabin cabinet cable cake calculate call camera camp campaign campus can Canadian cancer candidate cap capability capable capacity capital captain capture car carbon card care career careful carefully carrier carry case cash cast cat catch category Catholic cause ceiling celebrate celebration celebrity cell center central century CEO ceremony certain certainly chain chair chairman challenge chamber champion championship chance change changing channel chapter character characteristic characterize charge charity chart chase cheap check cheek cheese chef chemical chest chicken chief child childhood Chinese chip chocolate choice cholesterol choose Christian Christmas church cigarette circle circumstance cite citizen city civil civilian claim class classic classroom clean clear clearly client climate climb clinic clinical clock close closely closer clothes clothing cloud club clue cluster coach coal coalition coast coat code coffee cognitive cold collapse colleague collect collection collective college colonial color column combination combine come comedy comfort comfortable command commander comment commercial commission commit commitment committee common communicate communication community company compare comparison compete competition competitive competitor complain complaint complete completely complex complicated component compose composition comprehensive computer concentrate concentration concept concern concerned concert conclude conclusion concrete condition conduct conference confidence confident confirm conflict confront confusion Congress congressional connect connection consciousness consensus consequence conservative consider considerable consideration consist consistent constant constantly constitute constitutional construct construction consultant consume consumer consumption contact contain container contemporary content contest context continue continued contract contrast contribute contribution control controversial controversy convention conventional conversation convert conviction convince cook cookie cooking cool cooperation cop cope copy core corn corner corporate corporation correct correspondent cost cotton couch could council counselor count counter country county couple courage course court cousin cover coverage cow crack craft crash crazy cream create creation creative creature credit crew crime criminal crisis criteria critic critical criticism criticize crop cross crowd crucial cry cultural culture cup curious current currently curriculum custom customer cut cycle",
    "dad daily damage dance danger dangerous dare dark darkness data date daughter day dead deal dealer dear death debate debt decade decide decision deck declare decline decrease deep deeply deer defeat defend defendant defense defensive deficit define definitely definition degree delay deliver delivery demand democracy Democrat democratic demonstrate demonstration deny department depend dependent depending depict depression depth deputy derive describe description desert deserve design designer desire desk desperate despite destroy destruction detail detailed detect determine develop developing development device devote dialogue die diet differ difference different differently difficult difficulty dig digital dimension dining dinner direct direction directly director dirt dirty disability disagree disappear disaster discipline discourse discover discovery discrimination discuss discussion disease dish dismiss disorder display dispute distance distant distinct distinction distinguish distribute distribution district diverse diversity divide division divorce DNA do doctor document dog domestic dominant dominate door double doubt down downtown dozen draft drag drama dramatic dramatically draw drawing dream dress drink drive driver drop drug dry due during dust duty",
    "each eager ear early earn earnings earth ease easily east eastern easy eat economic economics economist economy edge edition editor educate education educational educator effect effective effectively efficiency efficient effort egg eight either elderly elect election electric electricity electronic element elementary eliminate elite else elsewhere e-mail embrace emerge emergency emission emotion emotional emphasis emphasize employ employee employer employment empty enable encounter encourage end enemy energy enforcement engage engine engineer engineering English enhance enjoy enormous enough ensure enter enterprise entertainment entire entirely entrance entry environment environmental episode equal equally equipment era error escape especially essay essential essentially establish establishment estate estimate etc ethics ethnic European evaluate evaluation even evening event eventually ever every everybody everyday everyone everything everywhere evidence evolution evolve exact exactly examination examine example exceed excellent except exception exchange exciting executive exercise exhibit exhibition exist existence existing expand expansion expect expectation expense expensive experience experiment expert explain explanation explode explore explosion expose exposure express expression extend extension extensive extent external extra extraordinary extreme extremely eye",
    "fabric facility face fact factor factory faculty fade fail failure fair fairly faith fall false familiar family famous fan fantasy far farm farmer fashion fast fat fate father fault favor favorite fear feature federal fee feed feel feeling fellow female fence few fewer fiber fiction field fifteen fifth fifty fight fighter fighting figure file fill film final finally finance financial find finding fine finger finish fire firm first fish fishing fit fitness five fix flag flame flat flavor flee flesh flight float floor flow flower fly focus folk follow following food foot football for force foreign forest forever forget form formal formation former formula forth fortune forward found foundation founder four fourth frame framework free freedom freeze French frequency frequent frequently fresh friend friendly friendship from front fruit frustration fuel full fully fun function fund fundamental funding funeral funny furniture furthermore future",
    "gain galaxy gallery game gang gap garage garden garlic gas gate gather gay gaze gear gender gene general generally generate generation genetic gentleman gently German gesture get ghost giant gift gifted girl girlfriend give given glad glance glass global glove go goal God gold golden golf good government governor grab grade gradually graduate grain grand grandfather grandmother grant grass grave gray great greatest green grocery ground group grow growing growth guarantee guard guess guest guide guideline guilty gun guy",
    "habit habitat hair half hall hand handful handle hang happen happy hard hardly hat hate have he head headline headquarters health healthy hear hearing heart heat heaven heavily heavy heel height helicopter hell hello help helpful her here heritage hero herself hey hi hide high highlight highly highway hill him himself hip hire his historian historic historical history hit hold hole holiday holy home homeless honest honey honor hope horizon horror horse hospital host hot hotel hour house household housing how however huge human humor hundred hungry hunter hunting hurt husband hypothesis",
    "I ice idea ideal identification identify identity ie if ignore ill illegal illness illustrate image imagination imagine immediate immediately immigrant immigration impact implement implication imply importance important impose impossible impress impression impressive improve improvement in incentive incident include including income incorporate increase increased increasing increasingly incredible indeed independence independent index Indian indicate indication individual industrial industry infant infection inflation influence inform information ingredient initial initially initiative injury inner innocent inquiry inside insight insist inspire install instance instead institution institutional instruction instructor instrument insurance intellectual intelligence intend intense intensity intention interaction interest interested interesting internal international Internet interpret interpretation intervention interview into introduce introduction invasion invest investigate investigation investigator investment investor invite involve involved involvement Iraqi Irish iron Islamic island Israeli issue it Italian item its itself",
    "jacket jail Japanese jet Jew Jewish job join joint joke journal journalist journey joy judge judgment juice jump junior jury just justice justify",
    "keep key kick kid kill killer killing kind king kiss kitchen knee knife knock know knowledge",
    "lab label labor laboratory lack lady lake land landscape language lap large largely last late later Latin latter laugh launch law lawn lawsuit lawyer lay layer lead leader leadership leading leaf league lean learn learning least leather leave left leg legacy legal legend legislation legitimate lemon length less lesson let letter level liberal library license lie life lifestyle lifetime lift light like likely limit limitation limited line link lip list listen literally literary literature little live living load loan local locate location lock long long-term look loose lose loss lost lot lots loud love lovely lover low lower luck lucky lunch lung",
    "machine mad magazine mail main mainly maintain maintenance major majority make maker makeup male mall man manage management manager manner manufacturer manufacturing many map margin mark market marketing marriage married marry mask mass massive master match material math matter may maybe mayor me meal mean meaning meanwhile measure measurement meat mechanism media medical medication medicine medium meet meeting member membership memory mental mention menu mere merely mess message metal meter method Mexican middle might military milk million mind mine minister minor minority minute miracle mirror miss missile mission mistake mix mixture mm-hmm mode model moderate modern modest mom moment money monitor month mood moon moral more moreover morning mortgage most mostly mother motion motivation motor mount mountain mouse mouth move movement movie Mr Mrs Ms much multiple murder muscle museum music musical musician Muslim must mutual my myself mystery myth",
    "naked name narrative narrow nation national native natural naturally nature near nearby nearly necessarily necessary neck need negative negotiate negotiation neighbor neighborhood neither nerve nervous net network never nevertheless new newly news newspaper next nice night nine no nobody nod noise nomination none nonetheless nor normal normally north northern nose not note nothing notice notion novel now nowhere n't nuclear number numerous nurse nut",
    "object objective obligation observation observe observer obtain obvious obviously occasion occasionally occupation occupy occur ocean odd odds of off offense offensive offer office officer official often oh oil ok okay old Olympic on once one ongoing onion online only onto open opening operate operating operation operator opinion opponent opportunity oppose opposite opposition option or orange order ordinary organic organization organize orientation origin original originally other others otherwise ought our ourselves out outcome outside oven over overall overcome overlook owe own owner",
    "pace pack package page pain painful paint painter painting pair pale Palestinian palm pan panel pant paper parent park parking part participant participate participation particular particularly partly partner partnership party pass passage passenger passion past patch path patient pattern pause pay payment PC peace peak peer penalty people pepper per perceive percentage perception perfect perfectly perform performance perhaps period permanent permission permit person personal personality personally personnel perspective persuade pet phase phenomenon philosophy phone photo photograph photographer phrase physical physically physician piano pick picture pie piece pile pilot pine pink pipe pitch place plan plane planet planning plant plastic plate platform play player please pleasure plenty plot plus PM pocket poem poet poetry point pole police policy political politically politician politics poll pollution pool poor pop popular population porch port portion portrait portray pose position positive possess possibility possible possibly post pot potato potential potentially pound pour poverty powder power powerful practical practice pray prayer precisely predict prefer preference pregnancy pregnant preparation prepare prescription presence present presentation preserve president presidential press pressure pretend pretty prevent previous previously price pride priest primarily primary prime principal principle print prior priority prison prisoner privacy private probably problem procedure proceed process produce producer product production profession professional professor profile profit program progress project prominent promise promote prompt proof proper properly property proportion proposal propose proposed prosecutor prospect protect protection protein protest proud prove provide provider province provision psychological psychologist psychology public publication publicly publish publisher pull punishment purchase pure purpose pursue push put",
    "qualify quality quarter quarterback question quick quickly quiet quietly quit quite quote",
    "race racial radical radio rail rain raise range rank rapid rapidly rare rarely rate rather rating ratio raw reach react reaction read reader reading ready real reality realize really reason reasonable recall receive recent recently recipe recognition recognize recommend recommendation record recording recover recovery recruit red reduce reduction refer reference reflect reflection reform refugee refuse regard regarding regardless regime region regional register regular regularly regulate regulation reinforce reject relate relation relationship relative relatively relax release relevant relief religion religious rely remain remaining remarkable remember remind remote remove repeat repeatedly replace reply report reporter represent representation representative Republican reputation request require requirement research researcher resemble reservation resident resist resistance resolution resolve resort resource respect respond respondent response responsibility responsible rest restaurant restore restriction result retain retire retirement return reveal revenue review revolution rhythm rice rich rid ride rifle right ring rise risk river road rock role roll romantic roof room root rope rose rough roughly round route routine row rub rule run running rural rush Russian",
    "sacred sad safe safety sake salad salary sale sales salt same sample sanction sand satellite satisfaction satisfy sauce save saving say scale scandal scared scenario scene schedule scheme scholar scholarship school science scientific scientist scope score scream screen script sea search season seat second secret secretary section sector secure security see seed seek seem segment seize select selection self sell Senate senator send senior sense sensitive sentence separate sequence series serious seriously serve service session set setting settle settlement seven several severe sex sexual shade shadow shake shall shape share sharp she sheet shelf shell shelter shift shine ship shirt shit shock shoe shoot shooting shop shopping shore short shortly shot should shoulder shout show shower shrug shut sick side sigh sight sign signal significance significant significantly silence silent silver similar similarly simple simply sin since sing singer single sink sir sister sit site situation six size ski skill skin sky slave sleep slice slide slight slightly slip slow slowly small smart smell smile smoke smooth snap snow so so - called soccer social society soft software soil solar soldier solid solution solve some somebody somehow someone something sometimes somewhat somewhere son song soon sophisticated sorry sort soul sound soup source south southern Soviet space Spanish speak speaker special specialist species specific specifically speech speed spend spending spin spirit spiritual split spokesman sport spot spread spring square squeeze stability stable staff stage stair stake stand standard standing star stare start state statement station statistics status stay steady steal steel step stick still stir stock stomach stone stop storage store storm story straight strange stranger strategic strategy stream street strength strengthen stress stretch strike string strip stroke strong strongly structure struggle student studio study stuff stupid style subject submit subsequent substance substantial succeed success successful successfully such sudden suddenly sue suffer sufficient sugar suggest suggestion suicide suit summer summit sun super supply support supporter suppose supposed Supreme sure surely surface surgery surprise surprised surprising surprisingly surround survey survival survive survivor suspect sustain swear sweep sweet swim swing switch symbol symptom system",
    "table tablespoon tactic tail take tale talent talk tall tank tap tape target task taste tax taxpayer tea teach teacher teaching team tear teaspoon technical technique technology teen teenager telephone telescope television tell temperature temporary ten tend tendency tennis tension tent term terms terrible territory terror terrorism terrorist test testify testimony testing text than thank thanks that the theater their them theme themselves then theory therapy there therefore these they thick thin thing think thinking third thirty this those though thought thousand threat threaten three throat through throughout throw thus ticket tie tight time tiny tip tire tired tissue title to tobacco today toe together tomato tomorrow tone tongue tonight too tool tooth top topic toss total totally touch tough tour tourist tournament toward towards tower town toy trace track trade tradition traditional traffic tragedy trail train training transfer transform transformation transition translate transportation travel treat treatment treaty tree tremendous trend trial tribe trick trip troop trouble truck true truly trust truth try tube tunnel turn TV twelve twenty twice twin two type typical typically",
    "ugly ultimate ultimately unable uncle under undergo understand understanding unfortunately uniform union unique unit United universal universe university unknown unless unlike unlikely until unusual up upon upper urban urge us use used useful user usual usually utility",
    "vacation valley valuable value variable variation variety various vary vast vegetable vehicle venture version versus very vessel veteran via victim victory video view viewer village violate violation violence violent virtually virtue virus visible vision visit visitor visual vital voice volume volunteer vote voter vs vulnerable",
    "wage wait wake walk wall wander want war warm warn warning wash waste watch water wave way we weak wealth wealthy weapon wear weather wedding week weekend weekly weigh weight welcome welfare well west western wet what whatever wheel when whenever where whereas whether which while whisper white who whole whom whose why wide widely widespread wife wild will willing win wind window wine wing winner winter wipe wire wisdom wise wish with withdraw within without witness woman wonder wonderful wood wooden word work worker working works workshop world worried worry worth would wound wrap write writer writing wrong",
    "xyst xanthic xenial xenon xebecs xylophone Xavier X-ray Xystos Xmas-tree Xanax",
    "yard yeah year yell yellow yes yesterday yet yield you young your yours yourself youth",
    "zone zed zing zipped zoning zone zonated zoons zoner zit zings zeal zonal zoo zooms zoon zoa zonate zones zooks zoos zero zins zymes zygoses zyme zooty zoic zips zees zaddik zoned zinced zincs zag zinc zin zags zips zee zenith zested zebra zebrawoods zettabyte zesty zeppelins zephyr zeilite zeniths zerks zestfully zester zeroth zeros zeroing zeroed ",
];

// SOURCE: https://blog.talaera.com/business-emails-phrases
export const sentences = [
    // BEING SOCIAL
    "I hope this email finds you well.",
    "I hope you had a good weekend.",
    "I hope you had a great trip.",
    "Hope you had a nice break.",
    "I hope you are well.",
    "I hope all is well.",
    "Hope you're enjoying your holiday.",
    "I hope you enjoyed the event.",
    "I'm glad we had a chance to chat at the convention.",
    "It was great to see you on Thursday.",
    "It was a pleasure to meet you yesterday.",
    // REASON OF THE EMAIL
    "I am writing to you about our last meeting.",
    "I am writing to you about your presentation.",
    "I am writing to you about our next event.",
    "I am writing to you with regards to...",
    "I am writing to you concerning...",
    "I am writing to you with regards regarding...",
    "I am writing to you in connection with...",
    // "I am writing to ask/enquire/let you know/confirm/check/invite you to/to update you on/ask for a favor...",
    "I am writing you to follow up on...",
    "I am contacting you to inform...",
    "I am reaching out because...",
    "This is just a quick note to...",
    "This is just a quick reminder...",
    "I wanted to let you know that...",
    "Might I take a moment of your time to... ",
    "This email is just to let you know that...",
    // REPLYING
    "I just got your request for...",
    "I just read your email about...",
    "As we discussed, I would like to send you...",
    "Thank you for your email about...",
    // "Thanks for your feedback on/your invitation/your suggestion",
    "Thanks for sending/asking about/attending",
    "Thanks for your quick reply.",
    "Thanks for getting back to me so quickly.",
    "Thank you for reaching out.",
    // APOLOGISING
    "Sorry for my late reply.",
    "Sorry that it took me so long to get back to you.",
    "I apologize for the late response.",
    "Sorry it’s been so long since my last email.",
    "I was sorry to hear about...",
    // "Please accept our apologies for any inconvenience caused.",
    // "Thank you for your understanding/for your patience.",
    // "Thanks again for your understanding/for your patience.",
    // "Once again, please accept our apologies for any inconvenience caused/for the inconvenience caused/for the delay/for the misunderstanding.",
    "I hope this is okay with you.",
    "I really hope we can find a solution soon.",
    "I hope you can understand.",
    "Sorry I couldn't be of more help.",
    // ATTACHMENTS AND INFORMATION
    "I’ve attached…",
    "Please find file attached.",
    "I'm enclosing ...",
    // "Please see the information below for more details about...",
    // "The parts in bold/in red/in blue are my comments/are the changes we made.",
    "Here's the document that you asked for,",
    "I’ve attached file for your review.",
    "I'm sending you file as a pdf file.",
    "The attached file contains...",
    // "Could you please sign the attached form and send it back to us by [date]?",
    "Here’s the document we discussed.",
    "[file] is attached.",
    "Please take a look at the attached file.",
    // "Take a look at the [file] I've attached to this email.",
    "More information is available at www.talaera.com.",
    "Please note that...",
    // REQUESTS AND INQUIRIES
    "Could you please...?",
    "Could you possibly tell me...?",
    "Can you please fill out this form?",
    "I'd really appreciate it if you could...",
    "I'd be very grateful if you could...",
    "It would be very helpful if you could send us/me...",
    // "I was wondering if you could/if you would be able to...",
    "If possible, I'd like to know more about...",
    "Please find my two main questions below.",
    // ASKING FOR CLARIFICATIONS
    "I didn't/don't fully understand.",
    "Could you please explain that again?",
    "I didn't quite get your point about something.",
    "Could you be more specific?",
    "Could you repeat what you said about...?",
    "Could you give us some more details on...?",
    // "If you could please shed some light on this topic, I would really appreciate it.",
    "Could you please clarify something?",
    // "Could you please clarify when you would like us to finish this?",
    // "When exactly are you expecting to have this feature?",
    "Here are the details on...",
    // "Could you please clarify what you would like us to do about...?",
    // "If I understood you correctly, you would like me to...",
    "What exactly do you mean by ...?",
    "Could you explain what you mean by ...?",
    "In other words, would you like us to...",
    // SHARING INFORMATION
    "Thank you for letting me know.",
    "Thank you for the heads up.",
    "Thank you for the notice.",
    "Please note...",
    "Quick reminder...",
    "Just a quick/friendly reminder that...",
    "Thank you for sharing.",
    "I'd like to inform you that...",
    "Just a quick heads up -",
    "Thanks for keeping me in the loop.",
    // "Please keep me informed/posted/updated/in the loop.",
    // GETTING AND GIVING APPROVAL
    "Please let me know if this is OK with you.",
    "Please let me know what you think.",
    "What are your thoughts on this?",
    "What do you think?",
    "We just need the thumbs up/the green light.",
    "You totally have the green light!",
    "Please guide me in this regard.",
    // "He approved of it, so you can go ahead with the project.",
    // SCHEDULING
    // "I'd like to schedule a meeting on Monday if you are available/free then.",
    // "I am available on Tuesday, if that's convenient for you.",
    // "Would you be available on Wednesday? If so, I'll send you an invite shortly.",
    // "Can you make it on Thursday? If so, I'll book accordingly.",
    // "I'm afraid I can't make it on Friday. How about Saturday?",
    // "(Due to...) I'm afraid we need to reschedule/delay/postpone/put back/cancel/call off/move/rearrange our meeting.",
    // "We are sorry to inform you that the interview/meeting scheduled for Monday will have to be rescheduled.",
    // GIVING BAD NEWS
    "Unfortunately, we cannot/we are unable to ...",
    "I'm afraid it will not be possible to...",
    "Unfortunately, I have to tell you that...",
    "I'm afraid that we can't...",
    "We regret to inform you that...",
    "I regret to inform you that due to...",
    // "After careful consideration, we have decided (not) to ...",
    "Due to reasons, it won't be possible to...",
    "It's against company policy to...",
    "I tried my best, but...",
    "Despite my best efforts, ...",
    "I can't see how...",
    "I'm sorry but it's out of my hands.",
    "I'm afraid I won't be able to...",
    "I'm sorry to tell you that...",
    // WHEN SOMETHING IS EXPECTED
    "Looking forward to hearing from you soon.",
    "I look forward to hearing from you soon.",
    "Please let me know if this works.",
    "Please let me know if you are available.",
    "Please let me know if that sounds good.",
    "Please let me know if you can.",
    "Please let me know if you need to reschedule...",
    "I look forward to seeing/meeting you.",
    "See you on Thursday/next week.",
    "Thanks.",
    "Thank you in advance.",
    "Thank you for everything.",
    "Cheers.",
    // "Any feedback you can give me on this would be greatly appreciated.",
    // "Any feedback you can give me on this would be highly appreciated.",
    // "Any feedback you can give me on this would be much appreciated.",
    // "If you could have it ready by tomorrow, I would really appreciate it.",
    // "If you could have it ready by the end of next week, I would really appreciate it.",
    "I would appreciate your help in this matter.",
    // OFFERING HELP OR INFORMATION
    "I hope you find this helpful.",
    "I hope it's clearer now.",
    "I hope that answers all your questions.",
    // "If we can be of any further assistance, please let us know.",
    "Let me know if you need any help.",
    "For further details...",
    "If you have any (more) questions (about)...",
    "In the meantime, if you need any more information,",
    // "If you need more information/more info/further information,",
    // "I know that's a lot to take in, so let me know if anything I've said doesn't make sense.",
    "please do not hesitate to contact me.",
    "please feel free to contact me/to get in touch.",
    "please let me know.",
    "drop me an email/drop me a line. ",
    // FRIENDLY WAYS TO SAY BYE
    "Best regards,",
    "All the best,",
    "Best wishes,",
    "Cheers, ",
    "Have a great weekend!",
    "Have a wonderful day!",
    // PANGRAMS
    "The five boxing wizards jump quickly.",
    "Pack my box with five dozen liquor jugs.",
    "Go, lazy fat vixen; be shrewd, jump quick.",
    "When zombies arrive, quickly fax Judge Pat.",
    "Amazingly few discotheques provide jukeboxes.",
    "Puzzled women bequeath jerks very exotic gifts.",
    "The quick onyx goblin jumps over the lazy dwarf.",
    "Brawny gods just flocked up to quiz and vex him.",
    "Watch “Jeopardy!”, Alex Trebek’s fun TV quiz game.",
    // "Six big devils from Japan quickly forgot how to waltz.",
    // "Five or six big jet planes zoomed quickly by the tower.",
    // "Jack amazed a few girls by dropping the antique onyx vase.",
    // "A quick movement of the enemy will jeopardize six gunboats.",
    // "Jaded zombies acted quaintly but kept driving their oxen forward.",
    // "No kidding—Lorenzo called off his trip to Mexico City just because they told him the conquistadors were extinct.",
    // "Quixotic jugglers repent; wave away fake methods and brazen mishaps.",
    "The quick brown fox jumps over a lazy dog.",
    "Mr. Jock, TV quiz PhD., bags few lynx.",
    "Two driven jocks help fax my big quiz.",
    "Waltz, nymph, for quick jigs vex Bud.",
    "My girl wove six dozen plaid jackets before she quit.",
    // "Sixty zippers were quickly picked from the woven jute bag.",
    "Sphinx of black quartz, judge my vow.",
    "A wizard’s job is to vex chumps quickly in fog.",
    // "Brown jars prevented the mixture from freezing too quickly.",
    "How vexingly quick daft zebras jump!",
    "Jackdaws love my big sphinx of quartz.",
    "GQ’s oft lucky whiz Dr. J, ex-NBA MVP.",
    // "We promptly judged antique ivory buckles for the next prize.",
    "Glib jocks quiz nymph to vex dwarf.",
    "When zombies arrive, quickly fax Judge Pat.",
    "Waxy and quivering, jocks fumble the pizza.",
    "The jay, pig, fox, zebra and my wolves quack!",
    "Pack my box with five dozen liquor jugs.",
    "The five boxing wizards jump quickly.",
    // "Farmer jack realized that big yellow quilts were expensive.",
];

// SOURCE: https://www3.nd.edu/~busiforc/handouts/cryptography/Letter%20Frequencies.html
export const bigrams = [
    "th",
    "he",
    "in",
    "en",
    "nt",
    "re",
    "er",
    "an",
    "ti",
    "es",
    "on",
    "at",
    "se",
    "nd",
    "or",
    "ar",
    "al",
    "te",
    "co",
    "de",
    "to",
    "ra",
    "et",
    "ed",
    "it",
    "sa",
    "em",
    "ro",
];

export const trigrams = [
    "the",
    "and",
    "tha",
    "ent",
    "ing",
    "ion",
    "tio",
    "for",
    "nde",
    "has",
    "nce",
    "edt",
    "tis",
    "oft",
    "sth",
    "men",
];

export const quadrigrams = [
    "that",
    "ther",
    "with",
    "tion",
    "here",
    "ould",
    "ight",
    "have",
    "hich",
    "whic",
    "this",
    "thin",
    "they",
    "atio",
    "ever",
    "from",
    "ough",
    "were",
    "hing",
    "ment",
];

export const topRow = [
    "Piroque",
    "Poutier",
    "Wipeout",
    "Equipt",
    "Equity",
    "Piquet",
    "Poetry",
    "Pouter",
    "Purity",
    "Pyrite",
    "Quoter",
    "Qwerty",
    "Roquet",
    "Torque",
    "Towery",
    "Troupe",
    "Typier",
    "Uptore",
    "Equip",
    "Erupt",
    "Outer",
    "Outre",
    "Pewit",
    "Piety",
    "Pique",
    "Pouty",
    "Power",
    "Purty",
    "Query",
    "Quiet",
    "Quire",
    "Quirt",
    "Quite",
    "Quoit",
    "Quote",
    "Repot",
    "Ropey",
    "Roque",
    "Route",
    "Tepoy",
    "Toper",
    "Toque",
    "Tower",
    "Towie",
    "Tripe",
    "Trope",
    "Twerp",
    "Twirp",
    "Twyer",
    "Uteri",
    "Wiper",
    "Write",
    "Wrote",
    "Etui",
    "Euro",
    "Peri",
    "Pert",
    "Pier",
    "Pity",
    "Poet",
    "Pore",
    "Port",
    "Pour",
    "Pout",
    "Prey",
    "Prow",
    "Pure",
    "Puri",
    "Pyre",
    "Pyro",
    "Quip",
    "Quit",
    "Repo",
    "Riot",
    "Ripe",
    "Rite",
    "Rope",
    "Ropy",
    "Rote",
    "Roti",
    "Roup",
    "Rout",
    "Ryot",
    "Tier",
    "Tire",
    "Tiro",
    "Tope",
    "Tore",
    "Tori",
    "Tory",
    "Tour",
    "Towy",
    "Trey",
    "Trio",
    "Trip",
    "Trop",
    "Trow",
    "Troy",
    "True",
    "Type",
    "Typo",
    "Tyre",
    "Tyro",
    "Weir",
    "Wept",
    "Wert",
    "Wipe",
    "Wire",
    "Wiry",
    "Wore",
    "Wort",
    "Writ",
    "Yeti",
    "Yore",
    "Your",
    "Yurt",
    "Ire",
    "Opt",
    "Ore",
    "Ort",
    "Our",
    "Out",
    "Owe",
    "Per",
    "Pet",
    "Pew",
    "Pie",
    "Pit",
    "Poi",
    "Pot",
    "Pow",
    "Pro",
    "Pry",
    "Pur",
    "Put",
    "Rep",
    "Ret",
    "Rip",
    "Roe",
    "Rot",
    "Row",
    "Rue",
    "Rut",
    "Rye",
    "Tie",
    "Tip",
    "Toe",
    "Top",
    "Tor",
    "Tow",
    "Toy",
    "Try",
    "Two",
    "Ute",
    "Wet",
    "Wit",
    "Woe",
    "Wot",
    "Wry",
    "Wye",
    "Yep",
    "Yet",
    "Yew",
    "Yip",
    "You",
    "Yow",
    "Yup",
];
export const homeRow = [
    "ashfalls",
    "hallahs",
    "ashfall",
    "daggas",
    // skalds	hallah	salads	flasks
    // flash	skald	kakas	slags
    // jaggs	galas	hadal	slash
    // shahs	gaffs	algal	dagga
    // flask	dahls	daffs	lakhs
    // shags	halls	glass	sagas
    // kasha	salad	galls	shall
    // dadas	falls	salsa	shads
    // flags	alfas	saga	half
    // sags	fads	dhal	glad
    // lash	kaka	lads	fall
    // hall	gads	alfa	adds
    // gags	gaga	hash	dahl
    // agha	hajj	lass	gaff
    // alga	dahs	asks	gals
    // lags	jagg	alas	jags
    // flak	daff	lakh	dash
    // gala
];
export const bottomRow = [
    // "bcnxv", "zxcm", "mbcnz", "bnvcnm", "zxcv", "vbnm", "mnxz", "nxv", "zmnx", "vbcn", "mvz", "vzxcmvx", "mnbxcvz"
    "zero",
    "zebra",
    "zigzag",
    "zipper",
    "zoo",
    "xenops",
    "xerox",
    "xiphias",
    "crony",
    "coal",
    "code",
    "cola",
    "vacuum",
    "vest",
    "violin",
    "volcano",
    "vote",
    "vowel",
    "balloon",
    "bee",
    "bird",
    "broom",
    "butterfly",
    "navigation",
    "net",
    "nine",
    "number",
    "mitten",
    "moon",
    "mouse",
];

// BEGINNER KEY LEVELS
export const keysLevel_1 = ["j", "f"];
export const keysLevel_2 = ["u", "r", "k"];
export const keysLevel_3 = ["d", "e", "i"];
export const keysLevel_4 = ["c", "g", "n"];
export const keysLevel_5 = ["t", "s", "l"];
export const keysLevel_6 = ["o", "b", "a"];
export const keysLevel_7 = ["v", "h", "m"];
export const keysLevel_8 = ["w", "x", "q"];
export const keysLevel_9 = ["y", "p", "z"];

export const keyLevelsArray = [
    keysLevel_1,
    keysLevel_2,
    keysLevel_3,
    keysLevel_4,
    keysLevel_5,
    keysLevel_6,
    keysLevel_7,
    keysLevel_8,
    keysLevel_9,
];
